[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pharma-dscsa-client"
version = "1.0.1"
description = "Official zero-dependency Python client for FDA DSCSA & EU FMD Drug Serialization API (21 USC 360eee) via RapidAPI"
readme = "README.md"
authors = [{ name = "Noor Mkdad" }]
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
keywords = ["fda-dscsa","eu-fmd","serialization","epcis","21-usc-360eee","gtin","track-and-trace","ndc-converter","pharma"]
dependencies = []

[project.urls]
"Homepage" = "https://noormkdad.com/tools/pharma-dscsa"
"Documentation" = "https://noormkdad.com/tools/pharma-dscsa"
"Marketplace" = "https://rapidapi.com/noor-mkdad-apis-noor-mkdad-apis-default/api/fda-dscsa-eu-fmd-drug-serialization-api-21-usc-360eee"
"Source" = "https://github.com/DrMkdaddy/pharma-dscsa-python"
